development:
  adapter: postgresql
  encoding: unicode
  database: rental2_db
  pool: 5
  username: acer
  password: postgres

  
test:
  adapter: postgresql
  encoding: unicode
  database: rental2_test_db
  pool: 5
  username: acer
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: rental2_pro_db
  pool: 5
  username: acer
  password: postgres